version: '3'
services:
  mTab:
    image: ghcr.io/crossgg/mtab:latest
    container_name: mTab
    ports:
      - "9200:80"
    volumes:
      - ./app:/app
    #  - ./data:/app/data
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    restart: unless-stopped
