version: '3'
services:
  mTab:
    image: itushan/php74:1.3
    container_name: mTabServers
    ports:
      - "3321:80"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    restart: always
