version: '3'
services:
  mTab:
    image: ghcr.io/crossgg/mtab:latest
    container_name: mTabServers
    ports:
      - "3321:80"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    restart: unless-stopped
