server {
	listen 80 default_server;
   	root /app/public;
	client_max_body_size 50M;
	#最大超时5分钟
	index index.php index.html index.htm default.php default.htm default.html;
	location ~ [^/]\.php(/|$) {
            try_files $uri =404;
            fastcgi_pass unix:/tmp/php-cgi-74.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            fastcgi_read_timeout 300;  # 设置 FastCGI 读取超时时间为 300 秒（5 分钟）
            fastcgi_connect_timeout 300;  # 设置 FastCGI 连接超时时间
            fastcgi_send_timeout 300;  # 设置 FastCGI 发送超时时间
    }

	location ~^/ {
    	if (!-e $request_filename){
    		rewrite  ^(.*)$  /index.php?s=$1  last;
    	}
    }

	location = /404.html {
		internal;
	}
}
